dist: trusty

language: node_js
node_js: '11'

env:
  global:
    - JAVA_HOME=/usr/lib/jvm/java-8-oracle
    - LANG=pt_BR.UTF-8
    - CHROME_BIN=google-chrome
    - VERSION-BUILD-TOOLS=27.0.3
    - VERSION-ANDROID=27

branches:
  only:
    - master
    - prod

notifications:
  email:
    on_success: never
    on_failure: change

matrix:
  include:
    - os: linux
      sudo: false
      language: android
      android:
        components:
          - build-tools-27.0.3
          - android-27
        licenses:
          - android-sdk-preview-.+
          - android-sdk-license-.+
          - google-gdk-license-.+
      addons:
        apt:
          sources:
            - sourceline: deb https://dl.yarnpkg.com/debian/ stable main
              key_url: https://dl.yarnpkg.com/debian/pubkey.gpg
          packages:
            - gradle
            - jq
            - oracle-java8-installer
            - oracle-java8-set-default


stages:
  - Code Analisys
  - Tests
  - Build
  - Deploy
  - Release

fast_finish: true

jobs:
  include:
    - stage: 'Code Analisys'
      name: 'Lint'
      script:
        - npm run lint

    - stage: 'Tests'
      name: 'Unit Tests'
      addons:
        sonarcloud:
          organization: 'brunodutr-github'
          token:
            secure: $SONAR_TOKEN
      cache:
        npm: true
        directories:
          - './node_modules'
          - '$HOME/.sonar/cache'
      script:
        - ng test --watch=false --progress=false --browsers=ChromeHeadlessCI --code-coverage

        - export VERSION=$(node -p -e "require('./package.json').version")

        - if [[ "$TRAVIS_BRANCH" != "prod" ]]; then
          export VERSION=${VERSION}-SNAPSHOT;
          fi

        - sonar-scanner -Dsonar.projectVersion=${VERSION}
          -Dsonar.links.homepage=https://github.com/${TRAVIS_REPO_SLUG}
          -Dsonar.links.ci=https://travis-ci.com/${TRAVIS_REPO_SLUG}
          -Dsonar.links.scm=https://github.com/${TRAVIS_REPO_SLUG}
          -Dsonar.links.issue=https://github.com/${TRAVIS_REPO_SLUG}/issues

    - name: 'e2e Tests'
      stage: 'Tests'
      cache:
        npm: true
        directories:
          - './node_modules'
      addons:
        sources:
          - sourceline: deb http://dl.google.com/linux/chrome/deb/ stable main
            key_url: https://dl-ssl.google.com/linux/linux_signing_key.pub
        packages:
          - google-chrome-stable
        update: true
      script:
        - npm install -g webdriver-manager
        - webdriver-manager update --standalone false --gecko false --versions.chrome 2.35
        - ng e2e --protractor-config=./e2e/protractor-ci.conf.js --webdriver-update=false

    - stage: 'Build'
      os: linux
      sudo: false
      language: android
      android:
        components:
          - build-tools-27.0.3
          - android-27
        licenses:
          - android-sdk-preview-.+
          - android-sdk-license-.+
          - google-gdk-license-.+
      addons:
        apt:
          sources:
            - sourceline: deb https://dl.yarnpkg.com/debian/ stable main
              key_url: https://dl.yarnpkg.com/debian/pubkey.gpg
          packages:
            - gradle
            - jq
            - oracle-java8-installer
            - oracle-java8-set-default
      before_install:
        - nvm install 11
        - npm install -g ionic cordova
      install:
        - npm install
      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -f  $HOME/.gradle/caches/transforms-1/transforms-1.lock
        - rm -rf $HOME/.gradle/caches/3.5/fileHashes/
        - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
      cache:
        npm: true
        directories:
          - '$HOME/.gradle/caches/'
          - '$HOME/.gradle/wrapper/'
          - '$HOME/.sonar/cache'
          - './node_modules'
      script:
        - ionic cordova build android --prod --release
        - ./travis/sign.sh
        

        
        - ./travis/before_deploy.sh

      deploy:
        provider: releases
        api_key:
          secure: '$GITHUB_TOKEN'
        file_glob: true
        file: ionictravis-${VERSION}.apk
        prerelease: '$SNAPSHOT'
        overwrite: '$SNAPSHOT'
        name: 'v${VERSION}'
        skip_cleanup: true
        on:
          repo: '$TRAVIS_REPO_SLUG'
          all_branches: true
          tags: false

    - stage: 'Deploy'
      install: skip
      script:
        - ./travis/before_deploy.sh

    - stage: 'Release'
      install: skip
      script:
        - ./travis/release.sh
      if: branch = prod
